config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
    collection do
      get 'inclimental_search'
    end
    collection do
      get 'search'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_form.html.erb
<%# 商品画像のプレビュー表示のためのスペース %>
<div id="previews"></div>
<%# /商品画像のプレビュー表示のためのスペース %>

<%# 商品画像 %>
<div class="img-upload">
  <div class="weight-bold-text">
    商品画像
    <span class="indispensable">必須</span>
  </div>
  <div class="click-upload">
    <p>
      クリックしてファイルをアップロード
    </p>
    <%= f.file_field :images, name: 'item_form[images][]', data: {index: 0} %>
  </div>
</div>
<%# /商品画像 %>

<%# 商品名と商品説明 %>
<div class="new-items">
  <div class="weight-bold-text">
    商品名
    <span class="indispensable">必須</span>
  </div>
  <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
  <div class="items-explain">
    <div class="weight-bold-text">
      商品の説明
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
  </div>
  <div class="tag-field">
    <div class="weight-bold-text">
      タグ
      <span class="indispensable">任意</span>
    </div>
    <%= f.text_field :tag_name, class:"items-text", placeholder: 'タグを追加' %>
    <%# タグの逐次検索の結果表示 %>
    <div id="search-result"></div>
    <%# /タグの逐次検索の結果表示 %>
  </div>
</div>
<%# /商品名と商品説明 %>

<%# 商品の詳細 %>
<div class="items-detail">
  <div class="weight-bold-text">商品の詳細</div>
  <div class="form">
    <div class="weight-bold-text">
      カテゴリー
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
    <div class="weight-bold-text">
      商品の状態
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:state_id, State.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
  </div>
</div>
<%# /商品の詳細 %>

<%# 配送について %>
<div class="items-detail">
  <div class="weight-bold-text question-text">
    <span>配送について</span>
    <a class="question" href="#">?</a>
  </div>
  <div class="form">
    <div class="weight-bold-text">
      配送料の負担
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:postage_id, Postage.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
    <div class="weight-bold-text">
      発送元の地域
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
    <div class="weight-bold-text">
      発送までの日数
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:shipping_date_id, ShippingDate.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
  </div>
</div>
<%# /配送について %>

<%# 販売価格 %>
<div class="sell-price">
  <div class="weight-bold-text question-text">
    <span>販売価格<br>(¥300〜9,999,999)</span>
    <a class="question" href="#">?</a>
  </div>
  <div>
    <div class="price-content">
      <div class="price-text">
        <span>価格</span>
        <span class="indispensable">必須</span>
      </div>
      <span class="sell-yen">¥</span>
      <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
    </div>
    <div class="price-content">
      <span>販売手数料 (10%)</span>
      <span>
        <span id='add-tax-price'></span>円
      </span>
    </div>
    <div class="price-content">
      <span>販売利益</span>
      <span>
        <span id='profit'></span>円
    </div>
    </span>
  </div>
</div>
<%# /販売価格 %>

<%# 注意書き %>
<div class="caution">
  <p class="sentence">
    <a href="#">禁止されている出品、</a>
    <a href="#">行為</a>
    を必ずご確認ください。
  </p>
  <p class="sentence">
    またブランド品でシリアルナンバー等がある場合はご記載ください。
    <a href="#">偽ブランドの販売</a>
    は犯罪であり処罰される可能性があります。
  </p>
  <p class="sentence">
    また、出品をもちまして
    <a href="#">加盟店規約</a>
    に同意したことになります。
  </p>
</div>
<%# /注意書き %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
      <li><%= link_to '商品検索', search_items_path, class: "search-list"%></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, new_user_session_path, class: "user-nickname" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_ichiran.html.erb
<% items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.images[0], class: "item-img" %>
            <% if item.order.present? %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
            <% end %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.name %>
            </h3>
            <div class='item-price'>
              <span><%= item.price %>円<br><%= item.postage.name %></span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>