config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
    collection do
      get 'inclimental_search'
    end
    collection do
      get 'search'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :order
  belongs_to :user
  has_many_attached :images
  has_many :comments
  has_many :item_tag_relations
  has_many :tags, through: :item_tag_relations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :state
  belongs_to :postage
  belongs_to :region
  belongs_to :shipping_date
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model
  attr_accessor( 
    :name, :description, :category_id, :state_id, :postage_id, :region_id, :shipping_date_id, :price, :user_id, :images,
    :id, :created_at, :datetime, :updated_at, :datetime,
    :tag_name
  )

  validates :name,             presence: true
  validates :description,      presence: true
  validates :category_id,      numericality: { other_than: 1, message: "を選択してください" }
  validates :state_id,         numericality: { other_than: 1, message: "を選択してください" }
  validates :postage_id,       numericality: { other_than: 1, message: "を選択してください" }
  validates :region_id,        numericality: { other_than: 1, message: "を選択してください" }
  validates :shipping_date_id, numericality: { other_than: 1, message: "を選択してください" }

  with_options presence: true, format: { with: /\A[0-9]+\z/ } do
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 },
                      presence: { message: "を入力してください" }
  end

  validates :images, presence: { message: "を選択してください" }
  validates :images, length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
  validates :user_id, presence: true

  def save
    # item情報を保存し、変数itemに代入
    item = Item.create(name: name, description: description, category_id: category_id, state_id: state_id, 
                      postage_id: postage_id, region_id: region_id, shipping_date_id: shipping_date_id, price: price, user_id: user_id, images: images)
    # first_or_initializeメソッドを使い、入力されたtagがデータベースにあればそれを選択し、新規ならば新規保存をし、結果を変数tagに代入
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    # tagを保存
    tag.save
    # 中間テーブルにitemとtagの紐付け情報を保存
    ItemTagRelation.create(item_id: item.id, tag_id: tag.id)
  end

  def update(params, item)
    #一度タグの紐付けを消すために中間テーブルの内容を削除
    item.item_tag_relations.destroy_all

    #paramsの中のタグの情報を削除。同時に、返り値として新たなタグの情報を変数に代入
    tag_name = params.delete(:tag_name)

    #もしタグの情報がすでに保存されていればインスタンスを取得、無ければインスタンスを新規作成
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?

    #タグを保存
    tag.save if tag_name.present?
    #商品を保存
    item.update(params)
    #中間テーブルに保存
    ItemTagRelation.create(item_id: item.id, tag_id: tag.id) if tag_name.present?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :check_item_and_user, only: [:edit, :destroy]

  def index
    @items = Item.includes(:user).order('created_at DESC')
  end

  def new
    @item_form = ItemForm.new
  end

  def create
    @item_form = ItemForm.new(item_form_params)
    if @item_form.valid?
      @item_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    # attributesメソッドで属性値をハッシュ形式で取得する
    item_attributes = @item.attributes
    # item_attributesを引数で受け取りインスタンスを生成
    @item_form = ItemForm.new(item_attributes)
    # itemに紐づくtagを取得
    @item_form.tag_name = @item.tags&.first&.tag_name
  end

  def update
    # ユーザーが編集後の内容をバリデーションにかけるため、新たにインスタンスを生成する
    @item_form = ItemForm.new(item_form_params)

    # 画像を選択し直さない場合は、自己代入演算子で@itemに紐づく画像をそのまま代入
    @item_form.images ||= @item.images.blobs

    if @item_form.valid? 
      @item_form.update(item_form_params, @item)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def inclimental_search
    # 新規出品、編集時のインクリメンタル検索用の処理
    return nil if params[:keyword] == ""
    tag = Tag.where(['tag_name LIKE ?', "%#{params[:keyword]}%"] )
    render json:{ keyword: tag }
    # /新規出品、編集時のインクリメンタル検索用の処理
  end

  def search
    # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    # ransakを用いた検索処理
    # 検索オブジェクトを作成し、ransakを利用したフォームから送られたデータを受け取る
    @q = Item.ransack(params[:q])
    # resultメソッドで検索結果を受け取る
    @items = @q.result
  end

  private

  def item_form_params
    params.require(:item_form).permit(:name, :description, :category_id, :state_id, :postage_id, :region_id, :shipping_date_id,
                  :price, :tag_name, {images: []}).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def check_item_and_user
    if current_user.id != @item.user_id || @item.order.present?
      redirect_to root_path
    end
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item_form, url: item_path, method: :patch, class: "form", local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%= render partial: "shared/form", locals: { f: f } %>

      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%=link_to 'もどる', "#", class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>

    <ul class='item-lists'>
      <%= render partial: "shared/ichiran", locals: { items: @items } %>

      <li class='list'>
        <% if @items.length == 0 %>
          <%= link_to '#' do %>
          <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              商品を出品してね！
            </h3>
            <div class='item-price'>
              <span>99999999円<br>(税込み)</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </li>
    </ul> 
  </div>
</div>

<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item_form, url: items_path, method: :post, class: "form", local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%= render partial: "shared/form", locals: { f: f } %>

      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "出品する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/search.html.erb
<h3>＜検索ページ＞</h3>
<h3><%= link_to 'トップページへ戻る', root_path%></h3>
<%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>
  <div class="search-field">
    <%= f.label :name, '商品名' %>
    <br>
    <%= f.text_field :name, placeholder: '商品名', value: params[:q]&.dig(:name) %>
  </div>
  <div class="search-field">
    <%= f.label :user_nickname_cont, '出品者名' %>
    <br>
    <%= f.text_field :user_nickname_cont, placeholder: '出品者名' %>
  </div>
  <div class="search-field">
    <%= f.label :category_id_in, 'カテゴリ' %>
    <br>
    <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name) %>
  </div>
  <div class="search-field">
    <%= f.label :price_gteq, '価格'%>
    <br>
    <%= f.number_field :price_gteq %> 円以上
    <br>
    <%= f.number_field :price_lteq %> 円以下
  </div>
  <%= f.submit '検索', class: "submit-btn" %>
<% end %>

<ul class='item-lists'>
  <%= render partial: "shared/ichiran", locals: { items: @items } %>
</ul>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.images[0], class:"item-box-img" %>
      <% if @item.order.present? %>
        <div class="sold-out">
          <span>Sold Out!!</span>
        </div> 
      <% end %>
    </div>
    <div class="other-images-content">
      <% @item.images[1..-1].each do |image| %>
        <div class="other-image">
          <%= image_tag image, class:"other-item-img"%>
        </div>
      <%end%>
    </div>

    <div class="item-price-box">
      <span class="item-price">
        <%= "¥#{@item.price}" %>
      </span>
      <span class="item-postage">
        <%= @item.postage.name %>
      </span>
    </div>

    <% if user_signed_in? &&  @item.order.blank? %>
      <% if current_user.id == @item.user_id %>
        <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
      <% else %>
        <%= link_to "購入画面に進む", item_orders_path(@item.id), method: :get ,class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.state.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.postage.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.region.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping_date.name %></td>
        </tr>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value"><%= @item.tags&.first&.tag_name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>

  <div id="comments">
    <h4>＜コメント一覧＞</h4>
      <% @item.comments.each do |comment| %>
        <div class="comment">
          <p class="user-info"><%= comment.user.nickname %>： </p>
          <p><%= comment.text%></p>
        </div>
      <% end %>
  </div>

  <div class="comment-box">
    <% if user_signed_in? %>
      <%= form_with model: [@item, @comment], id: "comment-form", local: true do |f| %>
        <%= f.text_area :text , class: "comment-text"%>
        <p class="comment-warn">
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <%= f.submit "コメントをする", class: "comment-btn" %>
      <% end %>
    <% end %>
  </div>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>